#spring config
spring:
  application:
    name: webService-client
  datasource:
    url: jdbc:mysql://27.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: chargedot
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 2
    maxActive: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    logSlowSql: true

#mybatis config
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: com.chargedot.webserviceclient.dao.mapper.*.xml
  type-aliases-package: com.chargedot.webserviceclient.dao.model

#logging config
logging:
  level:
    com.chargedot.webserviceclient.dao.mapper: debug
    com.chargedot.webserviceclient.client: info

#server config
server:
  port: 8543


