package com.chargedot.webservice.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-08-16T11:40:20.371+08:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "CommonService",
                  wsdlLocation = "http://localhost:8080/services/CommonService?wsdl",
                  targetNamespace = "http://service.webservice.chargedot.com/")
public class CommonService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.webservice.chargedot.com/", "CommonService");
    public final static QName CommonServiceImplPort = new QName("http://service.webservice.chargedot.com/", "CommonServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/services/CommonService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CommonService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/services/CommonService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CommonService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CommonService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CommonService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CommonService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CommonService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CommonServiceImpl
     */
    @WebEndpoint(name = "CommonServiceImplPort")
    public CommonServiceImpl getCommonServiceImplPort() {
        return super.getPort(CommonServiceImplPort, CommonServiceImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommonServiceImpl
     */
    @WebEndpoint(name = "CommonServiceImplPort")
    public CommonServiceImpl getCommonServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CommonServiceImplPort, CommonServiceImpl.class, features);
    }

}
