#project config
project:
  name: thinking
  version: 1.0.0
  copyrightYear: 2018
  profile: D:/profile/  #头像上传路径
#swagger config
swagger:
  url: http://127.0.0.1
  email: 834476422@qq.com
  basePackage: com.thinking.springbootincation.project
#server config
server:
  port: 5972
#spring config
spring:
  application:
    name: Thinking
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: chargedot
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 2
    maxActive: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    logSlowSql: true
  #kafka config
  kafka:
    bootstrap-servers: 192.168.1.243:9092
    consumer:
      group-id: springInAction
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  #redis config
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大空闲
        max-idle: 20
        #最大连接数
        max-active: 100
        #最大阻塞等待时间（负数表示没有限制）
        max-wait: 30000
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
  messages:
    #国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true

#mybatis config
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: com.thinking.springbootincation.project.**.**.mapper.*.xml
  type-aliases-package: com.thinking.springbootincation.project
#PageHelper config
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#logging config
logging:
  level:
    com.thinking.springbootincation.project: debug

#restTemplate time out config
rest:
  connectionRequestTimeout: 35000
  readTimeout: 35000
  connectTimeout: 35000

#schedule config
schedule:
  initialDelay: 10000
  fixedDelay: 10000

# Shiro config
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: char
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
